server:
  port: 9527
  tomcat:
    uri-encoding: UTF-8
    max-threads: 10
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  application:
    name: manage
#   数据源
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://139.9.71.142:3306/manage?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: zbf@970505
#  jpa:
#    show-sql: true
#    # 自动生成表结构
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#  # 文件大小上传配置
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB
#  jackson:
#    time-zone: GMT+8
#    serialization:
#      fail-on-empty-beans: false
#  # Actuator
#  management:
#    health:
#      status:
#        http-mapping:
#          DOWN: 200
#          OUT_OF_SERVICE: 200
#          FATAL: 200
#          UNKNOWN: 200
#      #
#      elasticsearch:
#        enabled: false
#    endpoint:
#      health:
#        show-details: always
#    endpoints:
#      web:
#        base-path: /actuator/
#        exposure:
#          include: '*'
## ivss设备地址配置
#ivss:
#  ip: 10.6.30.192
#  port: 37777
#  user: admin
#  passWord: Dccs12345.
##大华军工930平台地址
#dss:
#  username: dccs
#  password: Dccs12345.
#  server:
#    path: http://10.6.30.225
